version: '3.8'

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    env_file:
      - .env.prod
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  redisserver:
    depends_on:
        - mysqldb
    image: redis
    ports:
      - 6379:6379

  web:
    env_file:
      - .env.prod
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: ["/home/app/web/entrypoint_a.sh", "${DATABASE_HOST}:${DATABASE_PORT}", "-s", "-t", "20", "--", "gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:9000"]
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - redisserver
    expose:
      - 8000
      - 9000
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
    
    

volumes:
  mysql:
  mysql_config:
  static_volume:
  media_volume:   