version: '3.8'

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  redisserver:
    depends_on:
        - mysqldb
    image: redis
    ports:
      - 6379:6379

  web:
    env_file:
      - .env
    depends_on:
      - redisserver
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./core/:/app
    

volumes:
  mysql:
  mysql_config:

     