# Generated by Django 4.1 on 2022-11-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_unread_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('from_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destinatary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
