# Generated by Django 4.1.1 on 2022-09-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_user_1_chat_user_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
    ]
