# Generated by Django 4.1 on 2022-11-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='from_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatary', to=settings.AUTH_USER_MODEL),
        ),
    ]
