# Generated by Django 4.1.1 on 2022-10-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_last_message_group_last_message_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
