# Generated by Django 4.1 on 2022-12-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_notifications_from_to_alter_notifications_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='body',
            new_name='chat',
        ),
    ]
