# Generated by Django 4.1 on 2022-12-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_body_notifications_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_chat_notifications', to='chat.chat'),
        ),
    ]
