# Generated by Django 4.1.1 on 2022-10-04 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_2',
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
