# Generated by Django 4.1.4 on 2022-12-12 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 10, 33, 29, 863331)),
        ),
    ]
