# Generated by Django 4.1.1 on 2022-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='message',
            name='chats',
            field=models.ManyToManyField(related_name='chats', to='chat.chat'),
        ),
    ]
