# Generated by Django 4.1.1 on 2022-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_message_options_remove_message_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chats',
            field=models.ManyToManyField(related_name='messages', to='chat.chat'),
        ),
    ]
