# Generated by Django 4.1.1 on 2022-10-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_message_chats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
