# Generated by Django 4.1.1 on 2022-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
