# Generated by Django 4.1.1 on 2022-10-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chats',
            field=models.ManyToManyField(null=True, related_name='messages', to='chat.chat'),
        ),
    ]
