version: '3.8'

services:
  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_ch@t
      - MYSQL_DATABASE=db
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  redisserver:
    depends_on:
        - mysqldb
    image: redis
    ports:
      - 6379:6379

  web:
    depends_on:
      - redisserver
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    

volumes:
  mysql:
  mysql_config:

     